/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GameRouteImport } from './routes/game'
import { Route as PrestigeRouteImport } from './routes/prestige'
import { Route as RuleTestsRouteImport } from './routes/rule-tests'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RulesDocRouteImport } from './routes/rules-doc'
import { Route as SavesRouteImport } from './routes/saves'
import { Route as ApiDynastyAdvisorRouteImport } from './routes/api/dynasty-advisor'
import { Route as ApiSuggestTestRouteImport } from './routes/api/suggest-test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestigeRoute = PrestigeRouteImport.update({
  id: '/prestige',
  path: '/prestige',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleTestsRoute = RuleTestsRouteImport.update({
  id: '/rule-tests',
  path: '/rule-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesDocRoute = RulesDocRouteImport.update({
  id: '/rules-doc',
  path: '/rules-doc',
  getParentRoute: () => rootRouteImport,
} as any)
const SavesRoute = SavesRouteImport.update({
  id: '/saves',
  path: '/saves',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDynastyAdvisorRoute = ApiDynastyAdvisorRouteImport.update({
  id: '/api/dynasty-advisor',
  path: '/api/dynasty-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestTestRoute = ApiSuggestTestRouteImport.update({
  id: '/api/suggest-test',
  path: '/api/suggest-test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/game': typeof GameRoute
  '/prestige': typeof PrestigeRoute
  '/rule-tests': typeof RuleTestsRoute
  '/rules': typeof RulesRoute
  '/rules-doc': typeof RulesDocRoute
  '/saves': typeof SavesRoute
  '/api/dynasty-advisor': typeof ApiDynastyAdvisorRoute
  '/api/suggest-test': typeof ApiSuggestTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/game': typeof GameRoute
  '/prestige': typeof PrestigeRoute
  '/rule-tests': typeof RuleTestsRoute
  '/rules': typeof RulesRoute
  '/rules-doc': typeof RulesDocRoute
  '/saves': typeof SavesRoute
  '/api/dynasty-advisor': typeof ApiDynastyAdvisorRoute
  '/api/suggest-test': typeof ApiSuggestTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/game': typeof GameRoute
  '/prestige': typeof PrestigeRoute
  '/rule-tests': typeof RuleTestsRoute
  '/rules': typeof RulesRoute
  '/rules-doc': typeof RulesDocRoute
  '/saves': typeof SavesRoute
  '/api/dynasty-advisor': typeof ApiDynastyAdvisorRoute
  '/api/suggest-test': typeof ApiSuggestTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/game'
    | '/prestige'
    | '/rule-tests'
    | '/rules'
    | '/rules-doc'
    | '/saves'
    | '/api/dynasty-advisor'
    | '/api/suggest-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/game'
    | '/prestige'
    | '/rule-tests'
    | '/rules'
    | '/rules-doc'
    | '/saves'
    | '/api/dynasty-advisor'
    | '/api/suggest-test'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/game'
    | '/prestige'
    | '/rule-tests'
    | '/rules'
    | '/rules-doc'
    | '/saves'
    | '/api/dynasty-advisor'
    | '/api/suggest-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  GameRoute: typeof GameRoute
  PrestigeRoute: typeof PrestigeRoute
  RuleTestsRoute: typeof RuleTestsRoute
  RulesRoute: typeof RulesRoute
  RulesDocRoute: typeof RulesDocRoute
  SavesRoute: typeof SavesRoute
  ApiDynastyAdvisorRoute: typeof ApiDynastyAdvisorRoute
  ApiSuggestTestRoute: typeof ApiSuggestTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestige': {
      id: '/prestige'
      path: '/prestige'
      fullPath: '/prestige'
      preLoaderRoute: typeof PrestigeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-tests': {
      id: '/rule-tests'
      path: '/rule-tests'
      fullPath: '/rule-tests'
      preLoaderRoute: typeof RuleTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules-doc': {
      id: '/rules-doc'
      path: '/rules-doc'
      fullPath: '/rules-doc'
      preLoaderRoute: typeof RulesDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saves': {
      id: '/saves'
      path: '/saves'
      fullPath: '/saves'
      preLoaderRoute: typeof SavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dynasty-advisor': {
      id: '/api/dynasty-advisor'
      path: '/api/dynasty-advisor'
      fullPath: '/api/dynasty-advisor'
      preLoaderRoute: typeof ApiDynastyAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest-test': {
      id: '/api/suggest-test'
      path: '/api/suggest-test'
      fullPath: '/api/suggest-test'
      preLoaderRoute: typeof ApiSuggestTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  GameRoute: GameRoute,
  PrestigeRoute: PrestigeRoute,
  RuleTestsRoute: RuleTestsRoute,
  RulesRoute: RulesRoute,
  RulesDocRoute: RulesDocRoute,
  SavesRoute: SavesRoute,
  ApiDynastyAdvisorRoute: ApiDynastyAdvisorRoute,
  ApiSuggestTestRoute: ApiSuggestTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
